### PR TITLE
Use Travis CI to find syntax errors in Python code

### PR DESCRIPTION
**Pull request by cclauss**
Test results will be on https://travis-ci.com/humberry/ui-tutorial

### CODE REVIEW

**Comment by cclauss** [comment]
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).  Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python a __NameError__ is raised which will halt/crash the script on the user.

**Comment by humberry** [comment]
Travis CI: We couldn't find the repository humberry/ui-tutorial

**Comment by cclauss** [comment]
Activate it at https://travis-ci.com/humberry (login with GitHub credentials).

**Comment by humberry** [comment]
Already done, but it can‘t find the repo. I will try it tomorrow again.

**Comment by humberry** [comment]
No active repos are found...

**Comment by humberry** [comment]
Anyhow, thank you very much for the hint.

**Comment by cclauss** [comment]
Try going to __.org__, not __.com___... https://travis-ci.org/humberry (login with GitHub credentials).  I thought they had transferred everyone over to .com.  If you get into the repo, you might need to manually __Trigger the first build__ and after that it should be automatic.

Travis CI More options Trigger build

**Comment by humberry** [comment]
I tried .com and I also expand the url with /ui-tutorial. No active repo...
...so no chance for trigger build.

**Comment by humberry** [comment]
Ah okay, two times I have to enable Travis, sorry.

**Comment by cclauss** [comment]
It is working https://travis-ci.org/humberry/ui-tutorial  There are issues to fix up (print() function and xrange() --> range()) then the tests will go green.

**Pull request merged**
